# _config.yml
title: "TAL Crusade Ledger"
description: "A living log of our Warhammer 40k battles"
baseurl: "https://09peter.github.io/LedgerBot"      # if you’re publishing at https://<user>.github.io/<repo>, set this to "/<repo>"
url: "https://09peter.github.io"
theme: minima    # GitHub’s default theme—simple & responsive
paginate: 5      # posts per page
paginate_path: "/page:num/"
# ➞ Define a custom collection called 'reports'
collections:
  reports:
    output: true             # generate a page for each file
    permalink: /:collection/:path/