title: "TAL Crusade Ledger"
description: "A living log of our Warhammer 40k battles"
baseurl: "LedgerBot"        # or "/<repo>" if needed
url: "https://09peter.github.io"

theme: minima
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"

# Prefix all posts under /reports/ rather than root
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /reports/:year-:month-:day-:title/
